[package]
name = "anchor-idl-guard"
version = "0.1.0"
authors = ["Dean Little <dean@blueshift.gg>"]
description = "Created to fix Anchor"
edition = "2021"

[lib]
name = "anchor_idl_guard"

[dependencies]
anchor-lang = "<1.0.0"
five8_const = "1.0.0"